---
- name: "Setup e-mail for Jenkins"
  template:
    src: hudson.tasks.Mailer.xml.j2
    dest: "{{ cj_lib }}/hudson.tasks.Mailer.xml"
    owner: jenkins
    group: jenkins
    mode: 0644
  when: gmail is defined and (ansible_os_family == "Debian" or ansible_os_family == "RedHat")
