---
- name: "install deps"
  package:
    name: "{{ item }}"
    state: installed
  with_items:
    - "{{ cj_jenkins_deps }}"

- name: "Add jenkins rpm key"
  rpm_key:
    state: present
    key: "{{ cj_repo_key_url }}"

- name: "Add Jenkins rpm repo"
  get_url:
    url: "{{ cj_repo_url }}"
    dest: /etc/yum.repos.d/jenkins.repo

- name: "Enable yum caching considering jenkins rpm size"
  lineinfile:
    dest: /etc/yum.conf
    state: present
    regexp: '^keepcache=0'
    line: 'keepcache=1'
  when: cj_set_proxy is not defined

- name: "Set proxy in yum.conf"
  lineinfile:
    dest: /etc/yum.conf
    state: present
    regexp: '^proxy='
    line: 'proxy=http://{{ cj_proxy_host }}:{{ cj_proxy_port }}'
  when: (cj_set_proxy is defined) and (cj_set_proxy | bool)


- name: "Download specific Jenkins version"
  get_url:
    url: "{{ cj_repo_base_url_fixed_ver }}/jenkins-{{ cj_version }}-1.1.noarch.rpm"
    dest: "/tmp/jenkins-{{ cj_version }}-1.1.noarch.rpm"
  register: cj_fixed_version
  when: cj_version is defined

- name: "Check the version of Jenkins"
  stat:
    path: "/tmp/jenkins-{{ cj_version }}-1.1.noarch.rpm"
  register: cj_stat_version
  when: cj_version is defined

- name: "Install our specific version of Jenkins"
  package:
    name: "/tmp/jenkins-{{ cj_version }}-1.1.noarch.rpm"
    state: installed
  when: cj_version is defined and cj_stat_version.stat.exists

- name: "Jenkins package installed !?"
  package:
    name: jenkins
    state: present
  register: cj_pkg_installed

- name: "Install pip requierments"
  include: "cj-pip-reqs.yml"

- name: "Flush iptables"
  command: >
    iptables -F
  ignore_errors: true
