---

# allow customization from playbook | group_vars with noproxy_hosts var merge
- name: "If cj_no_proxy_hosts notset set it"
  set_fact:
    cj_no_proxy_hosts: []
  when: cj_no_proxy_hosts is not defined

- name: "If 127.0.0.1 not in noproxy_hosts or cj_no_proxy_hosts - append it"
  set_fact:
    cj_no_proxy_hosts:
      - '127.0.0.1'
  when: (noproxy_hosts is defined) and (('127.0.0.1' not in noproxy_hosts) or ('127.0.0.1' not in cj_no_proxy_hosts))

- name: "merge noproxy_hosts (if defined) with cj_no_proxy_hosts"
  set_fact:
    cj_no_proxy_hosts: "{{ noproxy_hosts }} + {{ cj_no_proxy_hosts }}"
  when: (noproxy_hosts is defined)

- name: "Filter duplicates"
  set_fact:
    cj_no_proxy_hosts: "{{ cj_no_proxy_hosts | unique }}"

- debug: var=cj_no_proxy_hosts

- name: "update Jenkins proxy setting"
  template:
    src: "proxy.xml.j2"
    dest: "{{ cj_proxy_conf_file }}"
    owner: "{{ cj_runas_user }}"
    group: "{{ cj_runas_group }}"
    mode: 0755
  register: proxy_config
