---
- hosts: repo-servers
  become: true
  vars:
    nexus_config_pypi: true
    nexus_config_docker: true
    nexus_config_raw: true
    nexus_config_rubygems: true
    nexus_config_bower: true
    nexus_config_npm: true

  roles:
    - role: oracle-java
    - role: shelleg.maven
    - role: shelleg.gradle
#    - role: shelleg.nexus3-oss


